<a href="https://colab.research.google.com/github/SettibathulaJyothi/Python-Aritificial-Intelligence-Code-417-Skill-Education-Class-10/blob/main/Creating%20an%20Array%20using%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Creating an Array using Numpy:**
Different ways to create an array using Numpy are as follows:

<font color=green> Creating one dimensional array:

In [ ]:
import numpy
rollno=numpy.array([1,2,3])
print(rollno)

[1 2 3]


<font color=green> Create a sequential 1D array with values as multiples of 10 from 10 to 100:

In [ ]:
import numpy as np
a=np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


<font color=green>Creating one-dimensional array with 4 randam values:

In [ ]:
import numpy as np
a=np.random.random(4)
print(a)

[0.18452989 0.5188018  0.40775633 0.23393226]


<font color=green>Creating two-dimensional array of  3 rows and 4 columns with random integer values less than 10:

In [ ]:
import numpy as np
a=np.random.randint(10,size=(3,4))
print(a)

[[0 4 0 4]
 [6 7 4 1]
 [4 4 7 9]]


<font color=green>Creating two-dimensional array of 3 rows and 4 columns with all ones as value:

In [ ]:
import numpy as np
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<font color=green>Creating two-dimensional array of 3 rows and 3 columns with all zeros as value:

In [ ]:
import numpy as np
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<font color=green>Creating two-dimensional array of 3 rows and 4 columns with all six as value:

In [ ]:
import numpy as np
a=np.full

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


<font color=green>we can create two dimensional (2-D) arrays by passing nested lists to the array() function

In [ ]:
import numpy as np
a=np.array([[15,'Pranay',96],[16,'pranya',92]])
print(a)

[['15' 'Pranay' '96']
 ['16' 'pranya' '92']]
