<a href="https://colab.research.google.com/github/SettibathulaJyothi/Python-Aritificial-Intelligence-Code-417-Skill-Education-Class-10/blob/main/Some%20Important%20Functions%20in%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Some Important Functions in Numpy**

**Type:** Type of an object i.e.array  

**Function:** type(ARR)

In [ ]:
import numpy as np
ARR=np.array((1,2,34))
print(type(ARR))

<class 'numpy.ndarray'>


**Type:** Check the dimensions of an array

**Function:** ARR.ndim

In [ ]:
import numpy as np
ARR=np.array(([1,2,3,4],[3,4,5,6]))
print(ARR.ndim)

2


**Type:** Shape of an array i.e.length of the array dimensions

**Function:** ARR.shape

In [ ]:
import numpy as np
ARR=np.array([[1,2,3,4],[3,4,5,6]])
print(ARR.shape)

(2, 4)


**Type:** Size of an array i.e.counts the number of elements.

**Function:** ARR.size

In [ ]:
import numpy as np
ARR=np.array([[1,2,3,4],[3,4,5,6]])
print(ARR.size)

8


**Type:** DataType of elements stored in the array

**Function:** ARR.dtype

In [ ]:
import numpy as np
ARR=np.array([[1,2,3,4],[3,4,5,6]])
print(ARR.dtype)

int64


**Type:** Maximum value in the element of the array\

**Function:** ARR.max()

In [ ]:
import numpy as np
ARR=np.array([[10,34,45,23,12]])
print(ARR.max())

45


**Type:** Row wise and column wise maximum value

**Function:** ARR.max(axis=1) for row\
&emsp;&emsp;&emsp;&emsp;&emsp;ARR.max(axis=0) for column

In [ ]:
import numpy as np
ARR=np.array([[11,2,13,4],[3,4,5,6]])
print("Rowwise max: ",ARR.max(axis=1))
print("Columnwise max: ",ARR.max(axis=0))

Rowwise max:  [13  6]
Columnwise max:  [11  4 13  6]


**Type:** Row wise and column wise minimum value

**Function:** ARR.min(axis=1) for row\
&emsp;&emsp;&emsp;&emsp;&emsp;ARR.min(axis=0) for column

In [ ]:
import numpy as np
ARR=np.array([[11,2,13,4],[3,4,5,6]])
print("Rowwise min: ",ARR.min(axis=1))
print("Columnwise min: ",ARR.min(axis=0))

Rowwise min:  [2 3]
Columnwise min:  [3 2 5 4]


**Type:** Sum of all values in the given array

**Function:** ARR.sum()

In [ ]:
import numpy as np
ARR=np.array([[11,2,13,4],[3,4,5,6]])
print("Row wise sum : ",ARR.sum(axis=1))
print("Column wise sum : ",ARR.sum(axis=0))
print("sum is :",ARR.sum())

Row wise sum :  [30 18]
Column wise sum :  [14  6 18 10]
sum is : 48


**Type:** Sorting the array

**Function:** ARR.sort()

In [ ]:
a=np.array([12.4,-10,23,29,15,-1,45,33,-14])
print(np.sort(a))
b=np.array([[-9,5,18,9,12],[10,11,3,-5,-10]])
print(np.sort(b,axis=1))
print(np.sort(b,axis=0))

[-14.  -10.   -1.   12.4  15.   23.   29.   33.   45. ]
[[ -9   5   9  12  18]
 [-10  -5   3  10  11]]
[[ -9   5   3  -5 -10]
 [ 10  11  18   9  12]]
